### ISSUE TITLE
ComboBox dropdown menu is not visible inside Dialog

### ISSUE THREAD

**Issue by saskliutas** [iTwin/iTwinUI#1061]
#### Describe the bug (actual behavior)

`ComboBox` does not show dropdown menu when rendered inside `Dialog` component and any of `Dialog` parent elements have `overflow: hidden` style.

#### Expected behavior

`ComboBox` dropdown menu should be visible when renderer inside Dialog.

#### Reproduction
Link to a minimal repro: 
https://codesandbox.io/s/itwinui-react-example-forked-5zn1df

##### Steps to reproduce
1. Press 'Open' button.
2. Expand `ComboBox`.
3. Dropdown is not visible.

**Comment by elephantcatdog** [comment]
@saskliutas Thank you for bringing this to our attention. I took a look into it and wasn't able to find a temporary solution to the problem. We'll discuss it at our next planning meeting.

**Comment by saskliutas** [comment]
I managed to workaround this by appending Dialog component to body using `createPortal`: https://codesandbox.io/s/itwinui-react-example-forked-xv61gh

**Comment by mayank99** [comment]
`createPortal` is the correct way to use Dialog (we use it by default in Modal). Other than that, this is also an unfortunate bug in tippy.js which is not maintained anymore. We are going to switch away from it in a future major version (#914).

Since there is nothing to do right now, I will close this issue. Thanks.
