### ISSUE TITLE
Stepper css issue with last element

### ISSUE THREAD

**Issue by Mindaugas-Adomavicius** [iTwin/iTwinUI#1090]
#### Describe the bug (actual behavior)
When using the Stepper component, the last element stepper.css clashes with other css defined in stepper.css. The result is a not transparent line that appears on the last step of the Stepper component.
![image](https://user-images.githubusercontent.com/100808732/220884693-6bdb1e64-31f8-4f15-aec6-2bb70cc8331b.png)

#### Expected behavior
The transparent line at the last step of Stepper.

##### Steps to reproduce
1. Use the Stepper component
1. Reach the final step
1. Additional line appears after the last step

#### Additional information
package version: "@itwin/itwinui-react": "^2.2.0",
Possible solution: fix the clashing css
![image](https://user-images.githubusercontent.com/100808732/220885046-8c5b1279-baf6-4276-9c06-724c0be478b8.png)

**Comment by mayank99** [comment]
Link to repro: https://itwin.github.io/iTwinUI/react/?path=/story/core-stepper--basic&args=currentStep:4

Seems like we need to change the order of CSS, so that this part comes after the `iui-current` modifier:
https://github.com/iTwin/iTwinUI/blob/46ee91ff9e50a1d4c9941df662af18c89ccca09b/packages/itwinui-css/src/stepper/stepper.scss#L43-L45

**Comment by mayank99** [comment]
@Mindaugas-Adomavicius Would you like to submit a PR for this?

**Comment by mayank99** [comment]
🚀 This is now fixed in 2.7.0
