### ISSUE TITLE
ComboBox options list is not inheriting its width from its parent

### ISSUE THREAD

**Issue by orlandoortegajr** [iTwin/iTwinUI#1155]
#### Describe the bug (actual behavior)
When we limit the width a ComboBox can take up by setting a maxWidth property, or even just width, what happens is that the list options will expand horizontally until it covers the last character of the longest option or up to some pre-determined width.

#### Expected behavior
It should inherit its width from the parent and any overflow should probably be shown as an ellipsis or perhaps handled in a different way as to prevent the horizontal width from expanding beyond that of the parent.

#### Reproduction
Link to a minimal repro: [(https://codesandbox.io/s/jovial-gianmarco-p2x0k5)](https://codesandbox.io/s/jovial-gianmarco-p2x0k5?file=/src/App.tsx)

##### Steps to reproduce
1. Introduce a ComboBox component with a maxWidth.
2. Build a list of options as shown in the repro were one of them has enough characters to exceed the width given to the ComboBox component.
3. See the bug happen when you click on the component and the container showing the list of options exceeds the specified width.

#### Additional information
N/A

**Comment by mayank99** [comment]
Hey @orlandoortegajr, this behavior is intentional so it's not a bug.

We have designed the combobox such that:
- the min-width of the dropdown is the same as the width of the input field.
- the max-width of the driodown is 2x the width of the input field, clamped by the viewport width.

This design was based on UX research so I wouldn't recommend trying to override it. However, if the users of your application have specifically complained about it, then we would love to hear it. Thanks.
