### ISSUE TITLE
Table Component horizontal overflow breaking row's border 

### ISSUE THREAD

**Issue by lima300** [iTwin/iTwinUI#1216]
#### Describe the bug (actual behavior)
I am using the Table  component, with only one column, inside a resizable InformationPanel. The text inside this column has to be only one line so I added a white-space: nowrap rule to that column's cells. When the InformationPanel width is shorter than the table it gets a horizontal scroll, but the rows' border does not go to the end of the text's div.

#### Reproduction
Link to a quick demo video

https://user-images.githubusercontent.com/45007067/233169878-88b75bea-bff8-45c2-9c3e-d3b10cb2b171.mp4

#### Additional information
I am using ItwinUi 1.48.2

**Comment by elephantcatdog** [comment]
Is it always the same width? I was able to add multi selection to our [horizontal scroll demo in storybook](http://localhost:6006/?path=/story/core-table--horizontal-scroll) and it seems to work fine there.

![image](https://user-images.githubusercontent.com/37936169/233211542-16d67259-a5b1-4870-b649-16017a466bb2.png)

Maybe try looking at the html there and see if rearranging your code to match that works. You could also look at our code in storybook here, but note that it is split up because of the medium (storybook).

It would be more helpful if you made a reproduction for us to look at.
