### ISSUE TITLE
Popover appends to the wrong element

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI#1256]
Noticed in ColorPicker that styles inside dropdown are broken:
![image](https://user-images.githubusercontent.com/83585998/236814776-37a2e77a-58c6-44bd-a8d0-0a81d5e6ba4b.png)

Happens because Tippy is being appended to body instead of iui-root.
First noticed in v2.5.0.

Sandbox: https://codesandbox.io/s/crazy-leavitt-6msbng?file=/src/App.tsx

**Comment by mayank99** [comment]
I just had an epiphany after hours. This bug is happening because of [dual package hazard](https://nodejs.org/api/packages.html#dual-commonjses-module-packages). Codesandbox uses CRA which prefers CJS, so if the Popover is imported from `esm/`, it doesn't use the same context as the `ColorPicker` (which is imported from `cjs/`).

So the user needs to change the Popover import.
```diff
- import { Popover } from "@itwin/itwinui-react/esm/core/utils";
+ import { Popover } from "@itwin/itwinui-react/cjs/core/utils";
```

Here's a fixed sandbox: https://codesandbox.io/s/infallible-rhodes-oe8ipu?file=/src/App.tsx

Alternatively, import all components explicitly from `esm/` (or `cjs/`. just be consistent).
```diff
- import { ThemeProvider, ColorPicker } from "@itwin/itwinui-react";
+ import { ThemeProvider, ColorPicker } from "@itwin/itwinui-react/esm";
```

or better yet, don't use our own internal Popover. \:)
