### ISSUE TITLE
IconButton: Label not displayed on disabled button

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1277]
The new functionality to show a tooltip using the `label` prop on an `<IconButton>` works well, but is confusing when a button is disabled. The disabled button does not show a tooltip, and a user may want to know what the button is supposed to do were it not disabled.

Previous to the change, we wrapped each of our buttons in a tooltip `<Tooltip><IconButton /></Tooltip>`. It is nicer to use the label property, but it removes the tooltip on disabled buttons.

https://codesandbox.io/s/itwin-base-forked-0y4ojo?file=/src/App.tsx

![Missing tooltip](https://github.com/iTwin/iTwinUI/assets/15036346/7287702e-f85a-48f0-ae71-901f186ce40a)

**Comment by mayank99** [comment]
@HaveSpacesuit Thanks for the issue. Unfortunately, fixing this would require a significant change from our side.

The root cause of this issue is that using the `disabled` attribute on a `<button>` element disables a bunch of DOM events that our Tooltip relies on. We partially worked around it by adding wrapping `<div>`s inside `<ButtonGroup>`, but it's still not reliable. See https://github.com/iTwin/iTwinUI-react/issues/30.

For a proper universal fix, we plan to handle this in two steps as part of our next major release:
- #391 
- #914

In the meantime, can continue using `<Tooltip><IconButton /></Tooltip>` on disabled buttons. If you choose to also use a wrapping `<Tooltip>` for non-disabled buttons, then ideally you would also provide a hidden label on the IconButton (using `aria-label` or `VisuallyHidden`).
