### ISSUE TITLE
ButtonGroup, Tabs: ResizeObserver loop limit error

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#1317]
#### Describe the bug (actual behavior)
In React 17, when a `ButtonGroup` size is contrained to a size where only the "overflowButton" is displayed, a "ResizeObserver loop limit" error display in the WebDev server overlay (that most iTwin.js application uses).

#### Expected behavior
No error should be raised as this is the intended behavior.

#### Reproduction
Link to a minimal repro: https://github.com/raplemie/itwinui-groupbutton-resizer-issue

##### Steps to reproduce
1. Resize the window so the button length crosses the 20% width of the window (green line)

#### Additional information

window.onerror will also report this error, I did not add to not make it feel like the "onerror" was the actual trigger of the overlay.
This can be seen by recreating the React17 setup in codesandbox.io and assigning `window.onerror = console.log;`, however in that case the overlay do not display, only the log.

**Comment by mayank99** [comment]
Description from #1318:

> #### Describe the bug (actual behavior)
> In React 17, when a tab is clicked in a `Tabs` component, a "ResizeObserver loop limit" error display in the WebDev server overlay (that most iTwin.js application uses).
> 
> #### Expected behavior
> No error should be raised as this is the intended behavior.
> 
> #### Reproduction
> Link to a minimal repro: https://github.com/raplemie/itwinui-tabs-resizer-issue
> 
> ##### Steps to reproduce
> 1. Click on tab "B"
> 
> ![image](https://github.com/iTwin/iTwinUI/assets/1904889/a32acd96-c863-47a9-9ac0-2cffa4e6b6a7)
> 
> 
> #### Additional information
> 
> see #1317, however in this case, nothing in the UI is actually changing.

**Comment by mattl-bentley** [comment]
@mayank99 I'm seeing a similar error with the Tab component on the latest 2x. Both when the tabs load or clicking tabs throws "ResizeObserver loop completed with undelivered notifications." This can be seen in [this sandbox ](https://codesandbox.io/p/sandbox/paging-page-refresh-forked-s62lcn)and viewing the console errors. Our app uses window.onerror to alert any undhandled errors.

Are there any plans to fix this for 2x/react 17?

**Comment by mayank99** [comment]
@mattl-bentley Please read though [my above response](https://github.com/iTwin/iTwinUI/issues/1317#issuecomment-1580828389) and follow the links I included. This is not a serious error and is safe to ignore. If you are deliberately surfacing errors using `window.error`, you should create an exception specifically for this particular error.

Also, it will not happen in `Tabs` in 3.x as we refactored it. We do plan to look at `ButtonGroup` too. Beyond that, you are welcome to contribute a fix if you have ideas.

**Comment by rohan-kadkol** [comment]
When I tried to clone and run the two repro repos included in this issue, here is what I found:

* https://github.com/raplemie/itwinui-groupbutton-resizer-issue (React 17)
  * `@itwin/itwinui-react@2.11.2` (version used in the repo): Reproducible
  * `@itwin/itwinui-react@2.12.21`: No error + no overflow button
  * `@itwin/itwinui-react@3.3.2`: No error + no overflow button
* https://github.com/raplemie/itwinui-tabs-resizer-issue (React 17)
  * `@itwin/itwinui-react@2.11.2` (version used in the repo): Reproducible
  * `@itwin/itwinui-react@2.12.21`: Reproducible
  * `@itwin/itwinui-react@3.3.2`: No error

So, the best thing for iTwinUI v2 users would be to upgrade to iTwinUI v3 (and preferably also to React 18, if on React 17).

---

Since the problem exists on React 17 regardless of the iTwinUI version, for the iTwinUI v3 + React 17 users, #1800 updated our internal usage of `ResizeObserver` to prevent cases where that benign error is thrown.

This is released in [v3.3.3](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin/itwinui-react%403.3.3)! 🎉
