### ISSUE TITLE
First menu item of dropdown has "focused" styling in Firefox 

### ISSUE THREAD

**Issue by linasburneika** [iTwin/iTwinUI#1391]
First menu item of dropdown has "focused" styling in Firefox the first time you open it, it's a blue border around it

#### Expected behavior
It should not have this border on menu item in Firefox. Chrome and chromium based flavours works as expected

#### Reproduction
Firefox v115.0b9  and v114 (https://itwinui.bentley.com/docs/dropdownmenu)
![image](https://github.com/iTwin/iTwinUI/assets/28901295/82804c57-1f79-4e0c-addc-1ab7891bd241)

Chrome v114.0.5735.199
![image](https://github.com/iTwin/iTwinUI/assets/28901295/00986598-15de-45ee-aac8-2772d8d7eff7)

**Comment by mayank99** [comment]
Hey @linasburneika, this is not a bug. It is expected that the focus will move to the first item when menu opens. This focus outline actually used to be visible in earlier versions of iTwinUI when [`:focus-visible`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) was not present in all browsers.

Currently, on Chrome/Safari we use `:has(:focus-visible)` for detecting the presence of `LinkAction` (this is a helper component which allows anchor links to fill up the space of the containing list item). Since [`:has`](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) is not available in Firefox and older versions of Chrome/Safari, we fallback to `:focus-within`, which does not make the distinction between mouse and keyboard events and therefore shows a focus outline for both. When Firefox adds support for `:has` (they promised ["first half of 2023"](https://bugzilla.mozilla.org/show_bug.cgi?id=418039#c62) but it's still unfinished), this outline should automatically disappear.
