### ISSUE TITLE
Progress Radial with "x-small" size goes out of containing div

### ISSUE THREAD

**Issue by joehenry9498** [iTwin/iTwinUI#1563]
#### Describe the bug (actual behavior)

ProgressRadial with size set to "x-small" goes out of containing div. If you set the width and height of the ProgressRadial smaller and smaller, it goes out of the div more and more. The first picture is with the height and width of the radial set to 16 pixels and the second is set to 10 pixels. It seems to have room in the containing div but does not stay in it.

![Screenshot 2023-09-12 095911](https://github.com/iTwin/iTwinUI/assets/70602409/619afae6-24c5-4edb-b7fb-2583473bcd95)
![Screenshot 2023-09-12 125752](https://github.com/iTwin/iTwinUI/assets/70602409/7fa4ef9b-0c0a-4711-ad1d-532c9ec07ebe)

#### Expected behavior

The ProgressRadial to stay inside of its containing div at all times.

#### Reproduction
Link to a minimal repro: 

Linked is a sandbox that demonstrates the issue https://codesandbox.io/s/optimistic-booth-k7w4pc?file=/src/App.tsx .

##### Steps to reproduce
1. Use a Progress Radial with size set to "x-small"
1. Color the background red
1. Watch it go out of the container

**Comment by mayank99** [comment]
the sandbox looks fine to me?
<img width="167" alt="" src="https://github.com/iTwin/iTwinUI/assets/9084735/257e1b0f-d9cc-4932-8276-64a432a79cd7">

**Comment by joehenry9498** [comment]
If you zoom on the top radial you can see where it slips out on the bottom of the div. Might be a little harder to see in dark mode. It will be more evident if you decrease the size of the radial more

**Comment by mayank99** [comment]
this is valid! i can see it better when zooming.

@joehenry9498 we can discuss how to fix it, but i want to first make sure that you're not trying to override the size using css. these sizes are pre-defined for consistency reasons and we cannot guarantee it will work if you change it to say, 10px

**Comment by joehenry9498** [comment]
> this is valid! i can see it better when zooming.
> 
> @joehenry9498 we can discuss how to fix it, but i want to first make sure that you're not trying to override the size using css. these sizes are pre-defined for consistency reasons and we cannot guarantee it will work if you change it to say, 10px

We are just using the regular "x-small" size and not overriding the css properties, the 10px example was just to showcase the problem more definitively

**Comment by mayank99** [comment]
@joehenry9498 We are currently working on our next major release (v3) and have completely refactored progress-radial, so this issue is actually fixed in v3. https://codesandbox.io/s/strange-kate-y567dt?file=/src/App.tsx

However, this should be a simple fix in v2, so would you like to contribute a fix to the `main` branch so it's available for you? I believe you'll just need to add `position: absolute` here: 
https://github.com/iTwin/iTwinUI/blob/6f24416899053c9de831ba2b7e898b9ac0f2b6d5/packages/itwinui-css/src/progress-indicator/radial.scss#L14-L16

We can discuss specifics / alternate solutions in your PR. You can look at our [contributing guide](https://github.com/iTwin/iTwinUI/blob/main/CONTRIBUTING.md) to get started.

**Comment by joehenry9498** [comment]
Pull request with fix is linked

**Comment by mayank99** [comment]
fix has been released in 2.11.8, thanks @joehenry9498
