### ISSUE TITLE
Missing animation inside Full page Modal.

### ISSUE THREAD

**Issue by siddhantrawal** [iTwin/iTwinUI#1770]
#### Describe the bug (actual behavior)

Animation is missing inside the full page modal: https://itwin.github.io/iTwinUI/react/?mode=preview&story=modal--full-page-modal

#### Reproduction
Link to a minimal repro: https://stackblitz.com/edit/github-mars6f-tjhviv?file=src%2FApp.tsx

**Comment by mayank99** [comment]
can you create a proper repro in stackblitz pinned to the current version?

**Comment by mayank99** [comment]
Reopening this because #1776 broke server-side rendering.
![image](https://github.com/iTwin/iTwinUI/assets/9084735/b6c38801-8174-4dc9-9633-d9fbc7580a73)

The `iui-dialog-visible` is not present on dialogs that are open by default (i.e. not opened by user).

Can be repro'd here: https://stackblitz.com/edit/github-mpgh1p?file=pages%2Findex.tsx

**Comment by mayank99** [comment]
Closing in favor of #1829.
