### ISSUE TITLE
`scrollbar-gutter` not working as a substitute for `padding-inline`

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#1801]
#### Describe the bug (actual behavior)

- `scrollbar-gutter: stable both-edges;` does not work as a substitute for `padding-inline` on Chrome Canary v123.0.6265.0.
![Screenshot 2024-01-29 at 11 31 37 AM](https://github.com/iTwin/iTwinUI/assets/849817/89f8f9af-b3d7-4f7c-be4b-73c64a27d932)

#### Expected behavior

- Inline padding should always be present despite which scrollbar is used (`::-webkit-scrollbar` vs `scrollbar`).

#### Reproduction

- Open [the surface demo page](https://itwin.github.io/iTwinUI/css/surface.html) in Chrome v121 or higher since [the scrollbar styling change](https://developer.chrome.com/docs/css-ui/scrollbar-styling) was made in browsers.

#### Additional information

- Might be worthwhile adding a new helper variable like `--iui-padding-inline: var(--iui-size-s);` so it is consistent across all UI components and could be changed by our dev users.

**Comment by mayank99** [comment]
This isn't directly related to Chrome 121. Here's what it looks like for me:
![image](https://github.com/iTwin/iTwinUI/assets/9084735/23c55f59-87b0-4eca-8e7e-11b439643c20)

The real reason for this issue is that some operating systems may choose to overlay scrollbars by default or because of some user preference or even depending on whether an external mouse is connected. For example, macOS and Windows both have a "Show scrollbars" setting. Android (and presumably other touchscreen operating systems) will never reserve scrollbar space regardless of the value of `scrollbar-gutter`.

The fix is to use both properties for their intended purposes, i.e. `padding-inline` for padding, and `scrollbar-gutter` for preventing layout shift when a region becomes scrollable. The side-effect is that we will end up with some extra space when combining these two properties, but that's better than the current misaligned/unpadded visual issues.
