### ISSUE TITLE
Pill Tabs change height on some transitions

### ISSUE THREAD

**Issue by Ben-Pusey-Bentley** [iTwin/iTwinUI#1878]
### Describe the bug (current behavior)

On the pills tab react story, changing the active tab from the third tab to any of the other two causes all of the tabs to become taller. 

https://github.com/iTwin/iTwinUI/assets/141063311/4c09fed0-5019-4571-80d8-595496a536bb

This appears to be caused by some unexplained changes in width when clicking from one tab to another. The issue only appears when the change is great enough, so narrow screens do not see this issue.

https://github.com/iTwin/iTwinUI/assets/141063311/5c77df05-43f3-466c-aaa7-cbcb09c1940c

### Expected Behavior

The tabs should remain the same height, regardless of what order they are made active in.

### Steps To Reproduce

1. Navigate to the React story for pill tabs.
2. Click on the third tab, then click on any of the other tabs.
3. If this does not work immediately, make sure the page is wide enough for the issue to occur.

**Comment by Ben-Pusey-Bentley** [comment]
@rohan-kadkol Can confirm that this issue is still happening, even with the changes on your PR that fix the other scrollbar tabs issue.

**Comment by mayank99** [comment]
Duplicating [this comment](https://github.com/iTwin/iTwinUI/pull/1873#pullrequestreview-1901044732) for visibility:

I believe this is happening because of the `useScrollbarGutter` hook added in #1733. I think we only need that hook for vertical tabs? Disabling it for horizontal tabs might fix this issue.

---

If this doesn't help, another thought I have is that the stripe should never participate in layout, because it is not part of the content (it's only decorative). The CSS [`contain`](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) property could maybe help here.
