### ISSUE TITLE
`Tooltip`s block click on `MenuItem`

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#1895]
### Describe the bug (current behavior)

Wrapping a `Tooltip` around a `MenuItem` inside a `DropdownMenu` blocks the click on the item.
```tsx
<DropdownMenu
  menuItems={(close) => [
    <Tooltip content="content">
      <MenuItem onClick={onClickHandler}>Item title</MenuItem> // will not click
    </Tooltip>
  // ...
```

Nesting the `Tooltip` inside the `MenuItem` prevents the tooltip from appearing.

```tsx
<DropdownMenu
  menuItems={(close) => [
    <MenuItem onClick={onClickHandler}>
      <Tooltip content="content"> // will not appear
          Item title
    </Tooltip>
  // ...
```

Inserting a `<span>` between the `Tooltip` and `MenuItem` allows both the tooltip to appear and the menu item to handle its click, but it is not easy to find this solution.

```tsx
<Tooltip content="content">
  <span>
    <MenuItem onClick={onClickHandler}>Item title</MenuItem>
  </span>
</Tooltip>
```

### Expected Behavior

Wrapping a `Tooltip` around a `MenuItem` should show a tooltip on hover and not block the menu item click.

### Link to minimal repro

https://stackblitz.com/edit/github-lx2rzk

### Steps To Reproduce

Wrap a tooltip around a menu item in a dropdown menu.

### Anything else?

@itwin/itwinui-react v3.5.0

**Comment by mayank99** [comment]
Thanks for reporting this.

Of all the cases you mentioned, these two are totally invalid and should not be used:

```jsx
<Tooltip>Text</Tooltip> // ❌
```

```jsx
<Tooltip>
  <span>…</span> // ❌
</Tooltip>
```

(See [docs](https://itwinui.bentley.com/docs/tooltip) for supported child elements)

The main issue about `MenuItem` is still valid and should be fixed:

```jsx
<Tooltip>
  <MenuItem>…</MenuItem>
</Tooltip>
```

However, for better UX, consider using a [sublabel](https://itwinui.bentley.com/docs/dropdownmenu#sublabel) instead of tooltip.

**Comment by HaveSpacesuit** [comment]
That's a great point about the sublabel, thanks! I'll see if it makes sense in our context.

**Comment by mayank99** [comment]
@HaveSpacesuit I spent some more time looking into it, and realized that you just need to pass a `value` to `MenuItem` make `onClick` work.

This is because:
- `Tooltip` (via floating-ui) merges event handlers and tries to check for certain properties of the `event` object.
- `Menuitem` invokes `onClick` with the `value` passed to it.

The combination of the two fails if you don't pass `value`.

![image](https://github.com/iTwin/iTwinUI/assets/9084735/7497f452-bfb3-433b-a2e2-c3183b9c8772)

<details>
<summary>See full corrected code</summary>

```tsx
<DropdownMenu
  menuItems={(close) => [
    <Tooltip content='Action 1' placement='right' key={1}>
      <MenuItem
        startIcon={<Svg2D />}
        onClick={() => {
          close();
          alert('Action 1');
        }}
        value={1}
      >
        Run 2D
      </MenuItem>
    </Tooltip>,
    <Tooltip content='Action 2' placement='right' key={2}>
      <MenuItem
        startIcon={<Svg3D />}
        onClick={() => {
          close();
          alert('Action 2');
        }}
        value={2}
      >
        Run 3D
      </MenuItem>
    </Tooltip>,
  ]}
>
  <IconButton aria-label='More options'>
    <SvgMore />
  </IconButton>
</DropdownMenu>
```
</details>

Hope that helps! And of course, sublabel will still work better than tooltips, so try using that if possible.

**Comment by HaveSpacesuit** [comment]
Oh, that's weird. Thanks for the explanation. I ended up going with the sublabels 🙂 but it's good to know this work around if I need it.
