### ISSUE TITLE
`DropdownMenu` close issue

### ISSUE THREAD

**Issue by GerardasB** [iTwin/iTwinUI#1924]
### Describe the bug (current behavior)

Close handler of the `menuItems` doesn't seem to close all the dropdown menu levels in _some_ cases.

### Expected Behavior

All dropdown menu popovers should close if `menuItems` function `close` is called.

### Link to minimal repro

https://stackblitz.com/edit/github-gaoklu?file=src%2FApp.tsx

### Steps To Reproduce

1. Click `Menu`
2. Hover `Item 1_3`
3. Hover `Item 2_3`
4. Hover `Item 3_3`
5. Click `Item 4_1`

Observe that the popover that contains `Item 1_3` is still open.

### Anything else?

- Repeating the steps for the second time (1 - 5 and then 2 - 5) will close the popovers correctly.
- Uncommenting `Item 1_2` will also make popovers close correctly.
- Less sub menu levels also make popovers close correctly.

**Comment by Ben-Pusey-Bentley** [comment]
Thanks for submitting this issue. I can reproduce this with your reproduction steps. Additionally, I can confirm that adding keys to the menu items and changing the `onClick` from `close` to `() => close()` do not fix this issue. This is certainly an issue on our end. Will raise it with the rest of the team.

**Comment by mayank99** [comment]
Looks like the main cause for this issue is here:

https://github.com/iTwin/iTwinUI/blob/40bd8ec6e48af283fc0880a6c3f0b9b874fba353/packages/itwinui-react/src/core/DropdownMenu/DropdownMenu.tsx#L86-L88

We want to move focus back to the element that triggered the menu, but in the case of submenu it turns out to be the parent menu-item rather than the button.

I wonder why it doesn't happen for three levels of menus though. 🤔

@GerardasB I also wonder what your use-case is for four levels of nested menus. Your users won't be happy if you subject them to such monstrosities 😅

**Comment by rohan-kadkol** [comment]
> I wonder why it doesn't happen for three levels of menus though. 🤔

When I put a `console.log()` in `close()`, I noticed that it was actually not being called at all when I clicked on "Item 4_2". So, I was investigating why that is the case.

One thing I noticed was that the current focus element (`document.activeElement`) changes the outcome. So, when I opened the menu the first time, the active element was "Item 1_3". Hovering through the submenu till "Item 4_2" and clicking it does not close the menu. But it also causes the activeElement to now become the body.

When the activeElement is the body, clicking "Item 4_2" closes the menu completely.

https://github.com/iTwin/iTwinUI/assets/45748283/fc128c7a-8c5c-4509-a7fe-55108e4fab0d

I also noticed that removing the `focus` trigger in MenuItem causes the menu to close correctly.

https://github.com/iTwin/iTwinUI/blob/40bd8ec6e48af283fc0880a6c3f0b9b874fba353/packages/itwinui-react/src/core/Menu/MenuItem.tsx#L130

Investigating this further.

---

> Looks like this issue is caused by this code:

I'm not sure I understood this. Because I think there's just one triggerRef and that is attached to the `children` of the `DropdownMenu`, which in this case is the button that triggered it.

https://github.com/iTwin/iTwinUI/blob/main/packages/itwinui-react/src/core/DropdownMenu/DropdownMenu.tsx#L112

**Comment by rohan-kadkol** [comment]
A quick update: After quite a bit of trial and error, I believe the issue is with the `isNestedSubmenuVisible` logic ([code](https://github.com/iTwin/iTwinUI/blob/6d0104a79ff25d869a884e4e11144224f18e4758/packages/itwinui-react/src/core/Menu/MenuItem.tsx#L121-L123)). Because of that issue, the submenu of the first `MenuItem` with a submenu (`Item 1_3` in this case) closes whenever we focus into level 4 (`Item 4_x`).

This is more apparent when navigating with the keyboard instead of the mouse:

https://github.com/iTwin/iTwinUI/assets/45748283/5e103925-3fc2-4d21-b976-99ba81a68460

---

I think your hunch is in the right direction. When I did a `mousedown`, the focus changed to `Item 4_2`. Due to the reason mentioned above, the submenu under `Item 1_3` closes upon changing the focus to `Item 4_2`. When `Item 4_2` does not exist, like you mentioned, the focus moves to `<body>`. Another consequence of the `Item 4_2` not existing is that the `onClick` (and thus also the `close()`) does not get called upon a `mouseup`.

https://github.com/iTwin/iTwinUI/assets/45748283/26bae9eb-8f80-4d3b-a254-df415fc30bf4

---

I believe once I fix the `isNestedSubmenuVisible` logic, the problem in this issue will be solved. Currently working on this.

**Comment by mayank99** [comment]
This is fixed in [3.10.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.10.0) 🚀

/cc @HaveSpacesuit I think you might benefit from this
