### ISSUE TITLE
Input field, declared in a dialog, does not autofocus

### ISSUE THREAD

**Issue by JeaNugroho** [iTwin/iTwinUI#2094]
### Describe the bug (current behavior)

There are multiple labeled input fields in a dialog, and the first field **is not** autofocused.

The first field already has a true autoFocus prop.
The dialog has been declared with both, setFocus and trapFocus props, to be true.

### Expected Behavior

There are multiple labeled input fields in a dialog, and the first field **is** autofocused

The first field has a true autoFocus prop.
The dialog has declared both, setFocus and trapFocus props, to be true.

### Link to minimal repro

https://stackblitz.com/edit/github-vs6lk3-hbpasi

### Steps To Reproduce

Using the "link to minimal repro" provided:

1. Open the dialog by clicking on the button, and
2. Notice the first of two fields in the dialog is not autofocused

![image](https://github.com/iTwin/iTwinUI/assets/35510082/860059fb-32fb-48f8-949b-2eee3c4ca053)

**Comment by mayank99** [comment]
Hey @JeaNugroho, thanks for the issue. This is a problem in your own code, as you're asking for multiple things to be focused at the same time. You should remove `setFocus` from the `Dialog` and `autoFocus` from the primary button.

```diff
@@ -12,7 +12,6 @@ export default function App() {
  <Dialog
    isOpen={isOpen}
    onClose={() => setIsOpen(false)}
-   setFocus={true}
    trapFocus={true}
    isDismissible
  >
@@ -28,7 +27,6 @@ export default function App() {
       <Button
         styleType='high-visibility'
         onClick={() => setIsOpen(false)}
-        autoFocus={true}
       >
         Primary
       </Button>
```

**Comment by HaveSpacesuit** [comment]
@mayank99 Can you clarify if using `trapFocus` is supposed to also make sure the dialog has the focus set, or does it only keep the focus once the user focuses the dialog?

In my testing, when a user clicks a button to open a dialog, the toolbar keeps the focus, and using TAB won't be limited to only dialog elements until the focus reaches the dialog. Once the dialog _does_ receive the focus, it is then trapped.

Is the the expected behavior?

Here is a sample repo. You can see if you click the blue button and then press tab - the other buttons are highlighted first.
https://stackblitz.com/edit/github-vs6lk3-zsiin4?file=src%2FApp.tsx

**Comment by mayank99** [comment]
Hey @HaveSpacesuit, thanks for the question. Let me try to clarify:
- `trapFocus` prevents focus from leaving the dialog when it's open
- `setFocus` moves focus into the dialog when opened (and moves it back when closed)
  - In my comment above, I suggested removing `setFocus` because there was other JS code moving focus into the Dialog.

We should probably default `setFocus` to `true` if `trapFocus` is set to `true`. Both of them are supposed to be used together when building a modal Dialog. Here's the full set of props that our `Modal` sets:

https://github.com/iTwin/iTwinUI/blob/5d313a763b5b5996664a3af14c8270e40dc07b72/packages/itwinui-react/src/core/Modal/Modal.tsx#L106-L118

We are planning to also add an `isModal` prop to `Dialog` to make this easier.

Hope that helps
