### ISSUE TITLE
itwinui-react: style.css CSS-SASS function collision when using react-scripts

### ISSUE THREAD

**Issue by AluminumAlman** [iTwin/iTwinUI#2272]
### Describe the bug (current behavior)

When using `react-scripts build` to build a project, importing `itwinui-react`'s `style.css` in a `.scss` file causes a CSS-SASS function collision anywhere where `filter:` is assigned `grayscale()` or `invert()`, signified by a call to a SASS function with a missing argument:
![image](https://github.com/user-attachments/assets/e99734c2-6a4b-4983-97f9-b3a1998e72f0)

This appears to be caused by by the build process for `styles.module.css` stripping function arguments when importing `itwinui-css`, an example of the arguments being stripped being https://github.com/iTwin/iTwinUI/blob/main/packages/itwinui-css/src/color-picker/color-picker.scss#L215:
Source:
![image](https://github.com/user-attachments/assets/ae8815b5-042a-445b-a5a9-365e4136d23c)
In `itwinui-react` `style.css` (de-minimized):
![image](https://github.com/user-attachments/assets/77d617b0-6f8f-4778-8864-3197bc7cd83a)

The issue could also be attributed using `react-scripts build`, but that package was last updated 2 years ago and it's unlikely that the project on which this issue was initially found will change its build process.

### Expected Behavior

Not getting an error about a missing argument when calling a SASS function.

### Link to minimal repro

https://stackblitz.com/edit/github-dcqt47?file=package.json

### Steps To Reproduce

1. Go to the minimal reproduction sandbox;
2. Run `npm run build` in the terminal;
3. Get the error:
![image](https://github.com/user-attachments/assets/4fb44a67-ce82-4dc5-a04c-417dd6dc0aed)

### Package Version

- [X] I'm using the latest version of iTwinUI.

### Anything else?

Not sure if it'd work, but perhaps a workaround for `filter:` `grayscale()` and `invert()` argument stripping during the build process of `styles.module.css` would be to assign a value that is more than 1 or 100%.

**Comment by mayank99** [comment]
Hey @AluminumAlman, thanks for opening this issue. This is not a bug in iTwinUI; the `invert()` and `grayscale()` functions work fine without any arguments; those arguments are getting stripped during our CSS minification step.

The actual problem here is that `react-scripts` is unnecessarily processing `.css` files through Sass. In a traditional webpack setup, the fix would be to _only_ process `.scss` files using `sass-loader`. You might want to [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) from `react-scripts` (or use something like [`craco`](https://github.com/dilanx/craco) as a last resort) and modify your webpack config. Or if you have the bandwidth, consider switching to a more modern bundler like [`vite`](https://vitejs.dev/) or [`rspack`](https://rspack.dev/).
