### ISSUE TITLE
Add css for info panel rows

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#292]
We need to provide classes for info panel elements. Either, some container class to style and align our inputs or something more specific.

**Comment by FlyersPh9** [comment]
Thinking about how we can pull this off. 🤔

When the information panel is narrow, we might want to show the information stacked rather than inline.  Examples from PlantSight:
![Screen Shot 2021-09-15 at 4 35 03 PM](https://user-images.githubusercontent.com/849817/133505644-d0981555-2367-41e8-9dbb-8b262f053bde.png)
![Screen Shot 2021-09-15 at 4 35 24 PM](https://user-images.githubusercontent.com/849817/133505686-5c22ddf5-ffd6-4b73-b241-3536b02d2855.png)

**Comment by FlyersPh9** [comment]
I've created #294 in draft.  I can think of 2 options using the current PR:
1. Use [the new `@container`](https://css-tricks.com/say-hello-to-css-container-queries/) to change the inputs from inline to stacked.
2. Use JS to apply/remove the `.iui-inline` class depending on the width of the info panel.

**Comment by bentleyvk** [comment]
> I've created #294 in draft. I can think of 2 options using the current PR:
> 
> 1. Use [the new `@container`](https://css-tricks.com/say-hello-to-css-container-queries/) to change the inputs from inline to stacked.
> 2. Use JS to apply/remove the `.iui-inline` class depending on the width of the info panel.

I think `@container` is still in development mode and you need to enable some flags in your browser for it to work. So the only choice is to use JS.

**Comment by FlyersPh9** [comment]
I've got #294 & #311, 2 different ways that we could maybe tackle this.  If anyone has any thoughts, I'd love to hear. @iTwin/itwinui

**Comment by mayank99** [comment]
> I've got #294 & #311, 2 different ways that we could maybe tackle this. If anyone has any thoughts, I'd love to hear. @iTwin/itwinui

Re: #311, what do you think of creating a separate `iui-input-label` component (as an alternative to the label in `iui-input-container`)? It would support both block and inline spacings, and then you could style that label for info-panel with just a few lines of CSS.
