### ISSUE TITLE
Vertical slider icons are misaligned

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#753]
Might need to do some cleanup and fixes on how things are spaced/aligned in the vertical slider.

_Originally posted by @veekeys in https://github.com/iTwin/iTwinUI/pull/718#pullrequestreview-1086899678_

**Comment by rohan-kadkol** [comment]
To confirm, do you mean having the top and bottom volume icons shifted slightly to the right so that the midpoint of the icon (green points) coincides with the line of the slider rail (red dotted lines)? Or are you referring to some other misalignment? 

![image](https://user-images.githubusercontent.com/45748283/187284887-0d12a191-1153-4292-884c-4923c48bd81d.png)

**Comment by mayank99** [comment]
@rohan-kadkol Yes that is the main issue but to fix the root cause I think we need a more robust solution for sizing and alignment. I see that currently we are setting a hardcoded width in the html. We can't expect our users to do the same so we should fix it.
https://github.com/iTwin/iTwinUI/blob/3b9b327ed8cf84db87dc1d61d356445cd5b051ba/packages/itwinui-css/backstop/tests/slider.html#L31-L33
