### ISSUE TITLE
Anchor link wrapping issue

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#845]
This code snippet has the anchor appear in a not ideal way:
```html
<label class="iui-checkbox-wrapper">
  <input
    class="iui-checkbox"
    type="checkbox"
  />
  <span class="iui-checkbox-label">I agree to the <a href="#" class="iui-anchor">terms of service</a>.</span>
</label>
```

**Results:**
![Screenshot 2022-12-08 at 3 25 53 PM](https://user-images.githubusercontent.com/849817/206560475-99e5f4c6-dc1d-4975-9ede-350bda42f24b.png)

Adding `display: contents;` appears to fix this, [suggested solution found here](https://stackoverflow.com/a/71008889).

**Comment by mayank99** [comment]
I wonder why we added `display: flex` to the checkbox-label. It works fine if we don't even use the `iui-checkbox-label` class.
```html
<input
    class="iui-checkbox"
    type="checkbox"
    id="checkbox-123"
  />
<label for="checkbox-123">I agree to the <a href="#" class="iui-anchor">terms of service</a>.</label>
```

`display: contents` is generally not advisable because it causes [accessibility issues](https://adrianroselli.com/2018/05/display-contents-is-not-a-css-reset.html#A11y), so it should be avoided.

**Comment by FlyersPh9** [comment]
I also noticed I could not focus the anchor link when placed within `<label>` which I guess does make sense.

**Comment by mayank99** [comment]
> I also noticed I could not focus the anchor link when placed within `<label>` which I guess does make sense.

Focusing works fine for me. Make sure you have an `href` on the anchor.
