### ISSUE TITLE
Table: Using undefined for last column width causes table body to scroll without header

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#893]
A table with `width: undefined` on the last column may scroll the table body more than the table header. Using `width: undefined` is helpful for situations when you may or may not have more columns than fit on the page, and it isn't known until runtime.

https://codesandbox.io/s/itwinui-react-minimal-example-forked-7wizuj?file=/src/columns.ts
![Extra table scroll](https://user-images.githubusercontent.com/15036346/196247403-34f9da06-75ae-4ac2-bb6a-f74ce83c1662.gif)

**Comment by mayank99** [comment]
I believe the main issue is fixed in [3.7.0](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.0), where we refactored the overflow handling so that the column header and rows always scroll together (#1891).

Now there is an open question of what should happen in the absence of explicit `width`. When there is no horizontal scroll, it expands to fill up the table width. But horizontal scroll itself depends on the columns occupying some space, so it cannot rely on implicit width. You will need to set a `minWidth` in that case. Once the data is loaded you can always adjust the minWidth if it ends up being too high.
