### ISSUE TITLE
Table: Horizontal scrollbar appears after resizing column and shrinking table 

### ISSUE THREAD

**Issue by medikornov** [iTwin/iTwinUI#895]
#### Describe the bug (actual behavior)
Resize the column and then shrink the table. A horizontal scrollbar appears and columns move out of view. Without resizing column, everything works fine.

#### Expected behavior
After resizing the column and then shrinking the table, horizontal scroll bar should not appear. Columns should shrink.

##### Steps to reproduce
1. Resize any column
2. Shrink table

**Comment by GintV** [comment]
Has any work started on this? Is there any work item in the backlog linked with this issue?

**Comment by gretanausedaite** [comment]
Hi @GintV, the work has not been started yet.

**Comment by FlyersPh9** [comment]
Hey @medikornov & @GintV, we spent some time looking into this and have determined that this is indeed working as was intended.  We're not considering this a regression because v1.38.1 didn't have full support for horizontal scrolling.  However we do see & understand the need for the option you are detailing.  When we rework our table in the next major version (expected in 2nd half of 2023), we'll look into offering an option to allow toggling either behavior and/or have "smart" detection that takes window resizing into account.

**Comment by GintV** [comment]
@FlyersPh9 Got it. If you're not considering this as a bug, can't this be converted to a feature? Or you already created a feature item for that in GitHub?

**Comment by FlyersPh9** [comment]
@GintV Yes, we had it as a backlog item that wasn't visible to non-team members.  I've changed it to an issue so it's visible to everyone now: #1144
