### ISSUE TITLE
Performance issue when many columns displayed

### ISSUE THREAD

**Issue by gioeau** [iTwin/iTwinUI#913]
#### Describe the bug (actual behavior)
When many columns are added to the table (in the hundreds), performance is hit severely.

#### Expected behavior
Performance shouldn't be hit so much by the number of columns in the table.

#### Reproduction
https://codesandbox.io/s/itwinui-react-minimal-example-forked-p1q6ih?file=/src/App.tsx

**Comment by rohan-kadkol** [comment]
Just to add on, you can also consider adding a column manager ([example](https://itwin.github.io/iTwinUI/react/?story=table--column-manager&theme=dark)) to show only a subset of columns at any time. If you feel that the column manager has some missing features for your use case (since you have many columns), you can voice your thoughts on a related issue (https://github.com/iTwin/iTwinUI/issues/783).

You can also try some suggestions mentioned in a similar issue about trying to improve the Table's performance (https://github.com/iTwin/iTwinUI/issues/888#issuecomment-1362950548). This might be pertinent because some of the performance issues in your playground is coming from the many *rows* rather than just the many *columns*.

**Comment by mayank99** [comment]
Yeah, column manager is probably the right move here. I don't think there's a good solution for performantly displaying hundreds of columns at the same time. This is a UX issue as much as a technical issue.
