### ISSUE TITLE
v3: Custom icon in Alert (composition)

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI#915]
developer.bentley.com wants to have custom alert icon
![image](https://user-images.githubusercontent.com/83585998/158962592-04bba54c-c2fa-45a6-90a4-7c74d4b14137.png)

**Comment by mayank99** [comment]
CSS is now stable so this is achievable if you bypass the `Alert` react component and use classes directly.

```jsx
<div class="iui-alert" data-iui-status="warning">

  /* this can be any icon */
  <svg class="iui-alert-icon">...</svg>

  <span class="iui-alert-message">
    This is a technical preview, etc
    <a class="iui-alert-link" href="/tech-preview-info">Learn more</a>
  </span>
</div>
```

As for React, we probably want to go for a composition API similar to Carousel or Dialog. Would play nicely with my subcomponent suggestion in #1013.

```jsx
<Alert>
  <Alert.Icon />
  <Alert.Content>...</Alert.Content>
  <Alert.Action>...</Alert.Action>
  <Alert.CloseButton>...</Alert.CloseButton>
</Alert>
```
(names are made up)

Unfortunately, this would be a breaking change because `children` can already be a ReactNode.
