### ISSUE TITLE
Backporting

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#966]
Step 0: figure out and document the process
Step 1: backport all the things

**Comment by mayank99** [comment]
Alright, I think I have a process finalized.

I've set up two branches: [`v0-css`](https://github.com/iTwin/iTwinUI/tree/v0-css) and [`v1-react`](https://github.com/iTwin/iTwinUI/tree/v1-react). These two branches will serve as the "source of truth" for itwinui-css `0.x` and itwinui-react `1.x`. Any changes that need to be released for those older versions can be made against that branch; I've set up CI to automatically run on PRs created against those branches, but I haven't made the CI passing a "hard" requirement, to avoid blocking PRs.

For releasing, there is no automation. Release can be done by manually running the "Publish to npm" workflow against either of the branches. This requires that you bump the version in package.json first (can even be done in the same PR). As an example, take a look at this PR: #1037. 

Also, the monorepo structure is a bit different. These legacy branches don't have the css and react in the same repo, so any changes that need to target both should be made separately. This is why we should only backport critical fixes that are small in scope. For best development experience, I suggest opening up a [codespace](https://github.com/features/codespaces) against the branch, or setting up a separate local clone/worktree. (If you only switch branches within the same monorepo, it will get a bit annoying as there will be lots of unrelated files left in source control).

Because the repo structure is so different, I expect that "cherry-picking" commits from `main` branch to either of these branches would be difficult, so any changes could instead be copied over to these branches manually and then PR'd.

**Comment by mayank99** [comment]
Closing this as we have decided _against_ backporting for the most part. Instead, we are focusing on making it as easy/smooth as possible to migrate to v2 (through #1031 and the migration tool). We'll document this in more detail in the future. For very specific edge cases where backporting is a hard requirement (e.g. critical fixes for an app that is simply unable to upgrade to v2 after trying), the above process remains the same.
