### ISSUE TITLE
Tile - moreOptions should stopPropagation

### ISSUE THREAD

**Issue by jzbuchalski** [iTwin/iTwinUI#985]
The onClick handler of the Tile component <Tile onClick={...} /> is called when the "..." more options dropdown is clicked.  As a result, my onClick handler is called when the dropdown is to be shown.  The dropdown menu should stopPropagation.

![image](https://user-images.githubusercontent.com/17307464/211704222-54ef6267-e8ad-4ba2-8b1b-af3ccd8c7f84.png)

**Comment by mayank99** [comment]
`stopPropagation` would fix the technical issue, but we need to consider **accessibility** here (related #840), and I would also question the UX of this. Interactive elements should not contain other interactive elements inside them.

**Comment by jzbuchalski** [comment]
Yes & no :-).  We use the cards to display a list of file attachments.  When a tile is selected, we open (preview) the attachment.  We also provide the context menu to perform other options, such as editing the description or deleting the attachment.  We certainly could create specific "hot spots" for clicking the thumbnail or the name (hyperlink), that would solve the problem.  

But I would argue since Tile selection is a clickable event, and the ability to show options is available, it's not on the component (or itwinui-react) to dictate how the component is used (UX).

**Comment by mayank99** [comment]
Sure, we can't stop anyone from shipping inaccessible experiences with our components, but we can try to encourage best practices and provide more accessible primitives.

In this case, I think can achieve an accessible version of what you want by using markup similar to this:

```html
<div class="iui-tile">
  ...
  <a href='...'>The name of the tile</a>
  ...
  <button>...</button>
</div>
```

This way, the dropdown button is not *inside* the anchor. And then we can use the pseudo-element trick mentioned in #840 to make the tile clickable based on the anchor.
```css
a::before {
  content: '';
  position: absolute;
  inset: 0;
}
```

In fact, you can achieve this today because `name` accepts a `ReactNode`: https://codesandbox.io/s/itwinui-react-minimal-example-forked-egcqjs?file=/src/App.tsx

And we're currently working on making this built into the component. We might actually deprecate the `onClick` prop as a result.

**Comment by jzbuchalski** [comment]
@mayank99 , I took your advise, and just created my own template.  Thanks for the background.
